apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coturn.fullname" . }}-coturn-config
  labels:
   {{- include "coturn.labels" . | nindent 4 }}
data:
  turnserver.conf: {{.Values.config | b64enc}}
