apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "coturn.fullname" . }}-controller
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 3478
      targetPort: turn-tcp
      protocol: TCP
      name: turn-tcp
    - name: tcp-proxy
      targetPort: tcp-proxy
      port: 5555
      protocol: TCP
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "coturn.fullname" . }}-controller
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 3478
      targetPort: turn-udp
      protocol: UDP
      name: turn-udp
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}

