{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "grpc-service.fullname" . }}
  labels:
    {{- include "grpc-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ .name }}
      kind: {{ .kind }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    {{- end }}

  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - "{{ . }}"
    {{- end }}

  rules:
    {{- range .Values.httpRoute.rules }}
    - backendRefs:
        {{- range .backendRefs }}
        - group: {{ .group }}
          kind: {{ .kind }}
          name: {{ .name }}
          port: {{ .port }} 
          weight: {{ .weight | default 1 }}  
        {{- end }}
      matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
        {{- end }}
    {{- end }}
{{- end }}