apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tusd.fullname" . }}
  labels:
    {{- include "tusd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tusd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: uploads-data
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tusd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tusd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: change-permissions
          image: alpine
          command:
            - chown
            - -R
            - 1000:1000
            - /srv/tusd-data/
          volumeMounts:
            - name: uploads-data
              mountPath: /srv/tusd-data/
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - tusd
            - -behind-proxy
          volumeMounts:
            - name: uploads-data
              mountPath: /srv/tusd-data/
          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 1080
          readinessProbe:
            httpGet:
              path: /
              port: 1080
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: uploads-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.volumeClaim }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}