apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.secretenv }}
  {{ $key | quote }}: {{ $value | toString | b64enc | quote }}
  {{- end }}